In [1]:
import pandas as pd
from pipeline import create_X_y_df, create_2_week_X_y_df
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import datetime

from features.Carl.utils import rolling_mean_per_userId, weekly_features

year_week,userId,number_of_downgrades_week_0,number_of_downgrades_week_1,number_of_downgrades_week_2,delta_week_0_1_number_of_downgrades,delta_week_0_1_%_number_of_downgrades,delta_week_1_2_number_of_downgrades,delta_week_1_2_%_number_of_downgrades,delta_variance_number_of_downgrades,delta_mean_number_of_downgrades,delta_variance_%_number_of_downgrades,delta_mean_%_number_of_downgrades
0,1000025,12.0,11.0,5.0,-1.0,-8.333333,-6.0,-54.545455,6.25,-3.5,533.890037,-31.439394
1,1000168,12.0,11.0,4.0,-1.0,-8.333333,-7.0,-63.636364,9.00,-4.0,764.606290,-35.984848
2,1000214,15.0,13.0,2.0,-2.0,-13.333333,-11.0,-84.615385,20.25,-6.5,1270.282709,-48.974359
3,1000248,9.0,14.0,6.0,5.0,55.555556,-8.0,-57.142857,42.25,-1.5,3175.233056,-0.793651
4,1000353,9.0,23.0,4.0,14.0,155.555556,-19.0,-82.608696,272.25,-2.5,14180.552638,36.473430
...,...,...,...,...,...,...,...,...,...,...,...,...
6084,1998678,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00,0.0,0.000000,0.000000
6085,1998931,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00,0.0,0.000000,0.000000
6086,1999022,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00,0.0,0.000000,0.000000
6087,1999164,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00,0.0,0.000000,0.000000
6088,1999847,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00,0.0,0.000000,0.000000

In [10]:
df_a = df_X.copy()

In [11]:
df_res = pd.DataFrame(
    data = {
        "userId": df_X["userId"].unique(),
    })

In [12]:
df_res = df_res.merge(df_pages_downgrade_rolling, on="userId", how = "left")

In [13]:
df_res = df_res.fillna(0.0)

In [14]:
df_res

,userId,number_of_downgrades_week_0,number_of_downgrades_week_1,number_of_downgrades_week_2,delta_week_0_1_number_of_downgrades,delta_week_0_1_%_number_of_downgrades,delta_week_1_2_number_of_downgrades,delta_week_1_2_%_number_of_downgrades,delta_variance_number_of_downgrades,delta_mean_number_of_downgrades,delta_variance_%_number_of_downgrades,delta_mean_%_number_of_downgrades
0,1749042,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1563081,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1697168,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1222580,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1714398,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
14915,1049171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14916,1065977,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14917,1354865,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14918,1182841,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14919,1946450,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0