In [1]:
import pandas as pd
from pipeline import create_X_y_df, create_2_week_X_y_df
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import datetime

from features.Carl.utils import rolling_mean_per_userId, weekly_features

In [2]:
df_full = pd.read_parquet("../../../data/churn-prediction-25-26/train.parquet")

In [3]:
df = df_full.copy()

In [4]:
df_X_slice_list, df_y_slice_list = create_2_week_X_y_df(df = df_full)

In [5]:
df_X = df_X_slice_list[0]

In [20]:
df_X["page"].unique()

array(['NextSong', 'Downgrade', 'Help', 'Home', 'Thumbs Up', 'Add Friend',
       'Thumbs Down', 'Add to Playlist', 'Logout', 'About', 'Settings',
       'Save Settings', 'Submit Downgrade', 'Roll Advert', 'Upgrade',
       'Error', 'Submit Upgrade'], dtype=object)

In [19]:
df_X[df_X["page"] == "Downgrade"]

df_X[(df_X["userId"] == "1749042") & (df_X["sessionId"] == 22683)]

,status,gender,firstName,level,lastName,userId,ts,auth,page,sessionId,location,itemInSession,userAgent,method,length,song,artist,time,registration,date
0,200,M,Shlok,paid,Johnson,1749042,1538352001000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",278,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,524.32934,Ich mache einen Spiegel - Dream Part 4,Popol Vuh,2018-10-01 00:00:01,2018-08-08 13:22:21,2018-10-01
992,200,M,Shlok,paid,Johnson,1749042,1538352525000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",279,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,178.02404,Monster (Album Version),Skillet,2018-10-01 00:08:45,2018-08-08 13:22:21,2018-10-01
1360,200,M,Shlok,paid,Johnson,1749042,1538352703000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",280,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,232.61995,Seven Nation Army,The White Stripes,2018-10-01 00:11:43,2018-08-08 13:22:21,2018-10-01
1825,200,M,Shlok,paid,Johnson,1749042,1538352935000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",281,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,265.50812,Under The Bridge (Album Version),Red Hot Chili Peppers,2018-10-01 00:15:35,2018-08-08 13:22:21,2018-10-01
2366,200,M,Shlok,paid,Johnson,1749042,1538353200000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",282,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,471.69261,Circlesong 6,Bobby McFerrin,2018-10-01 00:20:00,2018-08-08 13:22:21,2018-10-01
3271,200,M,Shlok,paid,Johnson,1749042,1538353671000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",283,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,266.86649,Who Can Compare,Foolish Things,2018-10-01 00:27:51,2018-08-08 13:22:21,2018-10-01
3802,200,M,Shlok,paid,Johnson,1749042,1538353937000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",284,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,1400.65914,Angel Dust,Gil Scott Heron,2018-10-01 00:32:17,2018-08-08 13:22:21,2018-10-01
6585,200,M,Shlok,paid,Johnson,1749042,1538355337000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",285,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,186.98404,Sweet And Dandy,Toots & The Maytals,2018-10-01 00:55:37,2018-08-08 13:22:21,2018-10-01
6675,200,M,Shlok,paid,Johnson,1749042,1538355388000,Logged In,Downgrade,22683,"Dallas-Fort Worth-Arlington, TX",286,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",GET,NaN,None,None,2018-10-01 00:56:28,2018-08-08 13:22:21,2018-10-01
6961,200,M,Shlok,paid,Johnson,1749042,1538355523000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",287,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,306.05016,On The Moon,Peter Cincotti,2018-10-01 00:58:43,2018-08-08 13:22:21,2018-10-01
7552,200,M,Shlok,paid,Johnson,1749042,1538355829000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",288,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,284.81261,Stay The Same,Bonobo Featuring Andreya Triana,2018-10-01 01:03:49,2018-08-08 13:22:21,2018-10-01
8148,200,M,Shlok,paid,Johnson,1749042,1538356113000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",289,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,275.12118,A Beggar On A Beach Of Gold,Mike And The Mechanics,2018-10-01 01:08:33,2018-08-08 13:22:21,2018-10-01
8702,200,M,Shlok,paid,Johnson,1749042,1538356388000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",290,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,199.49669,Captor Of Sin (Slayer Cover),At The Gates,2018-10-01 01:13:08,2018-08-08 13:22:21,2018-10-01
9133,200,M,Shlok,paid,Johnson,1749042,1538356587000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",291,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,175.25506,Tearing Everyone Down,Anti-Flag,2018-10-01 01:16:27,2018-08-08 13:22:21,2018-10-01
9479,200,M,Shlok,paid,Johnson,1749042,1538356762000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",292,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,241.39710,If You Were A Sailboat,Katie Melua,2018-10-01 01:19:22,2018-08-08 13:22:21,2018-10-01
9960,200,M,Shlok,paid,Johnson,1749042,1538357003000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",293,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,204.79955,Like You,Bow Wow,2018-10-01 01:23:23,2018-08-08 13:22:21,2018-10-01
10354,200,M,Shlok,paid,Johnson,1749042,1538357207000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",294,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,209.21424,Rock Wit U (Awww Baby),Ashanti,2018-10-01 01:26:47,2018-08-08 13:22:21,2018-10-01
10792,200,M,Shlok,paid,Johnson,1749042,1538357416000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",295,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,265.37751,Om Numah Shivaya,Apache Indian,2018-10-01 01:30:16,2018-08-08 13:22:21,2018-10-01
11373,200,M,Shlok,paid,Johnson,1749042,1538357681000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",296,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,213.34159,Always Remember,Train,2018-10-01 01:34:41,2018-08-08 13:22:21,2018-10-01
11832,200,M,Shlok,paid,Johnson,1749042,1538357894000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",297,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,270.88934,The Girl And The Robot,Royksopp,2018-10-01 01:38:14,2018-08-08 13:22:21,2018-10-01
12405,200,M,Shlok,paid,Johnson,1749042,1538358164000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",298,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,233.95220,24,Jem,2018-10-01 01:42:44,2018-08-08 13:22:21,2018-10-01
12912,200,M,Shlok,paid,Johnson,1749042,1538358397000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",299,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,202.37016,Nobody Puts Baby In The Corner,Fall Out Boy,2018-10-01 01:46:37,2018-08-08 13:22:21,2018-10-01
13350,200,M,Shlok,paid,Johnson,1749042,1538358599000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",300,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,319.65995,Christ Jesus,Deer Tick,2018-10-01 01:49:59,2018-08-08 13:22:21,2018-10-01
14054,200,M,Shlok,paid,Johnson,1749042,1538358918000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",301,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,219.45424,The Poison,Bullet For My Valentine,2018-10-01 01:55:18,2018-08-08 13:22:21,2018-10-01
14508,200,M,Shlok,paid,Johnson,1749042,1538359137000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",302,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,168.98567,Hints,JosÃÂ© GonzÃÂ¡lez,2018-10-01 01:58:57,2018-08-08 13:22:21,2018-10-01
14526,200,M,Shlok,paid,Johnson,1749042,1538359142000,Logged In,Help,22683,"Dallas-Fort Worth-Arlington, TX",303,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",GET,NaN,None,None,2018-10-01 01:59:02,2018-08-08 13:22:21,2018-10-01
14868,200,M,Shlok,paid,Johnson,1749042,1538359305000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",304,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,249.88689,HÃÂ©roe De Leyenda,HÃÂ©roes del Silencio,2018-10-01 02:01:45,2018-08-08 13:22:21,2018-10-01
14879,200,M,Shlok,paid,Johnson,1749042,1538359308000,Logged In,Home,22683,"Dallas-Fort Worth-Arlington, TX",305,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",GET,NaN,None,None,2018-10-01 02:01:48,2018-08-08 13:22:21,2018-10-01
15426,200,M,Shlok,paid,Johnson,1749042,1538359554000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",306,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,133.79873,Alphabet Aerobics,Blackalicious,2018-10-01 02:05:54,2018-08-08 13:22:21,2018-10-01
15727,200,M,Shlok,paid,Johnson,1749042,1538359687000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",307,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,224.57424,Human,The Killers,2018-10-01 02:08:07,2018-08-08 13:22:21,2018-10-01
16231,200,M,Shlok,paid,Johnson,1749042,1538359911000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",308,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,218.82730,On My Way,Phil Collins,2018-10-01 02:11:51,2018-08-08 13:22:21,2018-10-01
16716,200,M,Shlok,paid,Johnson,1749042,1538360129000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",309,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,233.69098,Invalid,Tub Ring,2018-10-01 02:15:29,2018-08-08 13:22:21,2018-10-01
17213,200,M,Shlok,paid,Johnson,1749042,1538360362000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",310,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,203.85914,Droplets,Colbie Caillat / Jason Reeves,2018-10-01 02:19:22,2018-08-08 13:22:21,2018-10-01
17660,200,M,Shlok,paid,Johnson,1749042,1538360565000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",311,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,259.99628,Lost Forever_ In the Blitzkrieg of Roses,Ordo Rosarius Equilibrio,2018-10-01 02:22:45,2018-08-08 13:22:21,2018-10-01
18204,200,M,Shlok,paid,Johnson,1749042,1538360824000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",312,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,363.38893,Octavo DÃÂ­a,Shakira,2018-10-01 02:27:04,2018-08-08 13:22:21,2018-10-01
18993,200,M,Shlok,paid,Johnson,1749042,1538361187000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",313,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,157.17832,Tu Solamente Tu,Selena,2018-10-01 02:33:07,2018-08-08 13:22:21,2018-10-01
19330,200,M,Shlok,paid,Johnson,1749042,1538361344000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",314,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,147.27791,Camp Hollers,Son House,2018-10-01 02:35:44,2018-08-08 13:22:21,2018-10-01
19648,200,M,Shlok,paid,Johnson,1749042,1538361491000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",315,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,315.48036,Odessa,Caribou,2018-10-01 02:38:11,2018-08-08 13:22:21,2018-10-01
20357,200,M,Shlok,paid,Johnson,1749042,1538361806000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",316,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,170.13506,Product Man,Swizz Beatz,2018-10-01 02:43:26,2018-08-08 13:22:21,2018-10-01
20755,200,M,Shlok,paid,Johnson,1749042,1538361976000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",317,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,196.91057,All Hands Against His Own,The Black Keys,2018-10-01 02:46:16,2018-08-08 13:22:21,2018-10-01
21226,200,M,Shlok,paid,Johnson,1749042,1538362172000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",318,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,302.65424,Radar Love,Golden Earring,2018-10-01 02:49:32,2018-08-08 13:22:21,2018-10-01
21960,200,M,Shlok,paid,Johnson,1749042,1538362474000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",319,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,184.94649,My Moon My Man,Feist,2018-10-01 02:54:34,2018-08-08 13:22:21,2018-10-01
22411,200,M,Shlok,paid,Johnson,1749042,1538362658000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",320,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,313.93914,Costruire,NiccolÃÂ² Fabi,2018-10-01 02:57:38,2018-08-08 13:22:21,2018-10-01
23221,200,M,Shlok,paid,Johnson,1749042,1538362971000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",321,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,191.08526,The Calculation (Album Version),Regina Spektor,2018-10-01 03:02:51,2018-08-08 13:22:21,2018-10-01
23710,200,M,Shlok,paid,Johnson,1749042,1538363162000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",322,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,243.98322,Torn,Natalie Imbruglia,2018-10-01 03:06:02,2018-08-08 13:22:21,2018-10-01
24323,200,M,Shlok,paid,Johnson,1749042,1538363405000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",323,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,213.70730,Unaffected,Hoobastank,2018-10-01 03:10:05,2018-08-08 13:22:21,2018-10-01
24330,307,M,Shlok,paid,Johnson,1749042,1538363406000,Logged In,Thumbs Up,22683,"Dallas-Fort Worth-Arlington, TX",324,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,NaN,None,None,2018-10-01 03:10:06,2018-08-08 13:22:21,2018-10-01

In [6]:
# Downgrade


df_pages = df_X[df_X["page"] == "Downgrade"]

In [7]:
df_pages_downgrade = df_pages.groupby(["userId", "date"])["page"].count().reset_index(name = "number_of_downgrades")

In [8]:
df_pages_downgrade_rolling = weekly_features(df = df_pages_downgrade, feature="number_of_downgrades")

In [9]:
df_pages_downgrade_rolling

year_week,userId,number_of_downgrades_week_0,number_of_downgrades_week_1,number_of_downgrades_week_2,delta_week_0_1_number_of_downgrades,delta_week_0_1_%_number_of_downgrades,delta_week_1_2_number_of_downgrades,delta_week_1_2_%_number_of_downgrades,delta_variance_number_of_downgrades,delta_mean_number_of_downgrades,delta_variance_%_number_of_downgrades,delta_mean_%_number_of_downgrades
0,1000025,12.0,11.0,5.0,-1.0,-8.333333,-6.0,-54.545455,6.25,-3.5,533.890037,-31.439394
1,1000168,12.0,11.0,4.0,-1.0,-8.333333,-7.0,-63.636364,9.00,-4.0,764.606290,-35.984848
2,1000214,15.0,13.0,2.0,-2.0,-13.333333,-11.0,-84.615385,20.25,-6.5,1270.282709,-48.974359
3,1000248,9.0,14.0,6.0,5.0,55.555556,-8.0,-57.142857,42.25,-1.5,3175.233056,-0.793651
4,1000353,9.0,23.0,4.0,14.0,155.555556,-19.0,-82.608696,272.25,-2.5,14180.552638,36.473430
...,...,...,...,...,...,...,...,...,...,...,...,...
6084,1998678,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00,0.0,0.000000,0.000000
6085,1998931,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00,0.0,0.000000,0.000000
6086,1999022,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00,0.0,0.000000,0.000000
6087,1999164,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00,0.0,0.000000,0.000000
6088,1999847,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00,0.0,0.000000,0.000000

In [10]:
df_a = df_X.copy()

In [11]:
df_res = pd.DataFrame(
    data = {
        "userId": df_X["userId"].unique(),
    })

In [12]:
df_res = df_res.merge(df_pages_downgrade_rolling, on="userId", how = "left")

In [13]:
df_res = df_res.fillna(0.0)

In [14]:
df_res

,userId,number_of_downgrades_week_0,number_of_downgrades_week_1,number_of_downgrades_week_2,delta_week_0_1_number_of_downgrades,delta_week_0_1_%_number_of_downgrades,delta_week_1_2_number_of_downgrades,delta_week_1_2_%_number_of_downgrades,delta_variance_number_of_downgrades,delta_mean_number_of_downgrades,delta_variance_%_number_of_downgrades,delta_mean_%_number_of_downgrades
0,1749042,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1563081,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1697168,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1222580,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1714398,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
14915,1049171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14916,1065977,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14917,1354865,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14918,1182841,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14919,1946450,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0