In [1]:
import pandas as pd
from pipeline import create_X_y_df

In [2]:
df_full = pd.read_parquet("../../data/churn-prediction-25-26/train.parquet")

In [3]:
df = df_full.copy()

In [4]:
# Second Train Test set
cut_off_date_train = pd.Timestamp("2018-11-05")
cut_off_date_test = pd.Timestamp("2018-11-15")

df_X, df_y = create_X_y_df(df = df,
                                t0=cut_off_date_train,
                                t1=cut_off_date_test)

In [5]:
df_X

,status,gender,firstName,level,lastName,userId,ts,auth,page,sessionId,location,itemInSession,userAgent,method,length,song,artist,time,registration,date
1,200,F,Vianney,paid,Miller,1563081,1538352002000,Logged In,NextSong,20836,"San Francisco-Oakland-Hayward, CA",9,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",PUT,238.39302,MiÃÂ©ntele,Los Bunkers,2018-10-01 00:00:02,2018-09-21 03:25:18,2018-10-01 00:00:02
448,200,F,Vianney,paid,Miller,1563081,1538352240000,Logged In,NextSong,20836,"San Francisco-Oakland-Hayward, CA",10,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",PUT,263.88853,Animal,Miike Snow,2018-10-01 00:04:00,2018-09-21 03:25:18,2018-10-01 00:04:00
945,200,F,Vianney,paid,Miller,1563081,1538352503000,Logged In,NextSong,20836,"San Francisco-Oakland-Hayward, CA",11,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",PUT,273.47546,Mi Corazon Continuara,Lorena,2018-10-01 00:08:23,2018-09-21 03:25:18,2018-10-01 00:08:23
1509,200,F,Vianney,paid,Miller,1563081,1538352776000,Logged In,NextSong,20836,"San Francisco-Oakland-Hayward, CA",12,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",PUT,284.86485,The Real Slim Shady,Eminem,2018-10-01 00:12:56,2018-09-21 03:25:18,2018-10-01 00:12:56
2066,200,F,Vianney,paid,Miller,1563081,1538353060000,Logged In,NextSong,20836,"San Francisco-Oakland-Hayward, CA",13,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",PUT,304.45669,The People In My Peephole,Claw Hammer,2018-10-01 00:17:40,2018-09-21 03:25:18,2018-10-01 00:17:40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24819307,200,F,Valeria,paid,Wright,1880093,1541364613000,Logged In,NextSong,2612,"New Orleans-Metairie, LA",22,"""Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebK...",PUT,243.90485,Let's Make Rock,Dream Evil,2018-11-04 20:50:13,2018-09-01 20:18:00,2018-11-04 20:50:13
24819309,307,F,Valeria,paid,Wright,1880093,1541364614000,Logged In,Thumbs Down,2612,"New Orleans-Metairie, LA",23,"""Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebK...",PUT,NaN,None,None,2018-11-04 20:50:14,2018-09-01 20:18:00,2018-11-04 20:50:14
24819407,200,F,Valeria,paid,Wright,1880093,1541364856000,Logged In,NextSong,2612,"New Orleans-Metairie, LA",24,"""Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebK...",PUT,217.57342,Eleanor (Digital Album Version),JET,2018-11-04 20:54:16,2018-09-01 20:18:00,2018-11-04 20:54:16
24819410,307,F,Valeria,paid,Wright,1880093,1541364857000,Logged In,Thumbs Down,2612,"New Orleans-Metairie, LA",25,"""Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebK...",PUT,NaN,None,None,2018-11-04 20:54:17,2018-09-01 20:18:00,2018-11-04 20:54:17
24819412,307,F,Valeria,paid,Wright,1880093,1541364858000,Logged In,Logout,2612,"New Orleans-Metairie, LA",26,"""Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebK...",PUT,NaN,None,None,2018-11-04 20:54:18,2018-09-01 20:18:00,2018-11-04 20:54:18

In [11]:
df_a = df_X[["userId", "level"]].drop_duplicates()

In [12]:
df_a = df_a.merge(df_y, on = "userId")

In [13]:
df_a

        userId level  Cancellation Confirmation
0      1563081  paid                          0
1      1697168  paid                          0
2      1697168  free                          0
3      1714398  paid                          0
4      1010522  paid                          0
...        ...   ...                        ...
22380  1306591  paid                          0
22381  1910265  paid                          0
22382  1662561  paid                          0
22383  1880093  free                          0
22384  1880093  paid                          0

[22385 rows x 3 columns]

In [14]:
print(len(df_a[(df_a["gender"] == "F") & (df_a["Cancellation Confirmation"] == 1)]) / len(df_a[df_a["gender"] == "F"]))
print(len(df_a[(df_a["gender"] == "F") & (df_a["Cancellation Confirmation"] == 0)]) / len(df_a[df_a["gender"] == "F"]))
print(len(df_a[(df_a["gender"] == "M") & (df_a["Cancellation Confirmation"] == 1)]) / len(df_a[df_a["gender"] == "M"]))
print(len(df_a[(df_a["gender"] == "M") & (df_a["Cancellation Confirmation"] == 0)]) / len(df_a[df_a["gender"] == "M"]))

KeyError: 'gender'

In [15]:
print(len(df_a[(df_a["level"] == "paid") & (df_a["Cancellation Confirmation"] == 1)]) / len(df_a[df_a["level"] == "paid"]))
print(len(df_a[(df_a["level"] == "paid") & (df_a["Cancellation Confirmation"] == 0)]) / len(df_a[df_a["level"] == "paid"]))
print(len(df_a[(df_a["level"] == "free") & (df_a["Cancellation Confirmation"] == 1)]) / len(df_a[df_a["level"] == "free"]))
print(len(df_a[(df_a["level"] == "free") & (df_a["Cancellation Confirmation"] == 0)]) / len(df_a[df_a["level"] == "free"]))

0.061793045664013405
0.9382069543359866
0.05071278336059827
0.9492872166394017