In [1]:
import pandas as pd
from pipeline import create_X_y_df
import numpy as np

In [2]:
df_full = pd.read_parquet("../../data/churn-prediction-25-26/train.parquet")

In [3]:
df = df_full.copy()

In [4]:
# Second Train Test set
cut_off_date_train = pd.Timestamp("2018-11-05")
cut_off_date_test = pd.Timestamp("2018-11-15")

df_X, df_y = create_X_y_df(df = df,
                                t0=cut_off_date_train,
                                t1=cut_off_date_test)

In [20]:
df_X["device_used"] = df_X["userAgent"].apply(lambda x:  x[x.index("("): x.index(")") + 1])

In [21]:
df_X

,status,gender,firstName,level,lastName,userId,ts,auth,page,sessionId,...,userAgent,method,length,song,artist,time,registration,date,device_used,exact_device
1,200,F,Vianney,paid,Miller,1563081,1538352002000,Logged In,NextSong,20836,...,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",PUT,238.39302,MiÃÂ©ntele,Los Bunkers,2018-10-01 00:00:02,2018-09-21 03:25:18,2018-10-01 00:00:02,(Macintosh; Intel Mac OS X 10_9_4),Macintosh
448,200,F,Vianney,paid,Miller,1563081,1538352240000,Logged In,NextSong,20836,...,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",PUT,263.88853,Animal,Miike Snow,2018-10-01 00:04:00,2018-09-21 03:25:18,2018-10-01 00:04:00,(Macintosh; Intel Mac OS X 10_9_4),Macintosh
945,200,F,Vianney,paid,Miller,1563081,1538352503000,Logged In,NextSong,20836,...,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",PUT,273.47546,Mi Corazon Continuara,Lorena,2018-10-01 00:08:23,2018-09-21 03:25:18,2018-10-01 00:08:23,(Macintosh; Intel Mac OS X 10_9_4),Macintosh
1509,200,F,Vianney,paid,Miller,1563081,1538352776000,Logged In,NextSong,20836,...,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",PUT,284.86485,The Real Slim Shady,Eminem,2018-10-01 00:12:56,2018-09-21 03:25:18,2018-10-01 00:12:56,(Macintosh; Intel Mac OS X 10_9_4),Macintosh
2066,200,F,Vianney,paid,Miller,1563081,1538353060000,Logged In,NextSong,20836,...,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",PUT,304.45669,The People In My Peephole,Claw Hammer,2018-10-01 00:17:40,2018-09-21 03:25:18,2018-10-01 00:17:40,(Macintosh; Intel Mac OS X 10_9_4),Macintosh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24819307,200,F,Valeria,paid,Wright,1880093,1541364613000,Logged In,NextSong,2612,...,"""Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebK...",PUT,243.90485,Let's Make Rock,Dream Evil,2018-11-04 20:50:13,2018-09-01 20:18:00,2018-11-04 20:50:13,(Windows NT 6.3; WOW64),Windows
24819309,307,F,Valeria,paid,Wright,1880093,1541364614000,Logged In,Thumbs Down,2612,...,"""Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebK...",PUT,NaN,None,None,2018-11-04 20:50:14,2018-09-01 20:18:00,2018-11-04 20:50:14,(Windows NT 6.3; WOW64),Windows
24819407,200,F,Valeria,paid,Wright,1880093,1541364856000,Logged In,NextSong,2612,...,"""Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebK...",PUT,217.57342,Eleanor (Digital Album Version),JET,2018-11-04 20:54:16,2018-09-01 20:18:00,2018-11-04 20:54:16,(Windows NT 6.3; WOW64),Windows
24819410,307,F,Valeria,paid,Wright,1880093,1541364857000,Logged In,Thumbs Down,2612,...,"""Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebK...",PUT,NaN,None,None,2018-11-04 20:54:17,2018-09-01 20:18:00,2018-11-04 20:54:17,(Windows NT 6.3; WOW64),Windows
24819412,307,F,Valeria,paid,Wright,1880093,1541364858000,Logged In,Logout,2612,...,"""Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebK...",PUT,NaN,None,None,2018-11-04 20:54:18,2018-09-01 20:18:00,2018-11-04 20:54:18,(Windows NT 6.3; WOW64),Windows

In [22]:
def device_type(s: str):
    if "Windows" in s:
        return "Windows"
    elif "Macintosh" in s:
        return "Macintosh"
    elif "Linux" in s:
        return "Linux"
    elif "iPad" in s:
        return "iPad"
    elif "iPhone" in s:
        return "iPhone"
    else:
        return "Different Device"

In [23]:
df_X["exact_device"] = df_X["device_used"].apply(device_type)

In [40]:
df_a = df_X[["userId", "exact_device"]]

In [41]:
df_b = df_a.drop_duplicates()

In [46]:
df_b

           userId exact_device
1         1563081    Macintosh
2         1697168    Macintosh
4         1714398      Windows
5         1010522      Windows
6         1475659      Windows
...           ...          ...
24727427  1004668      Windows
24729155  1306591      Windows
24751626  1910265        Linux
24766737  1662561      Windows
24817606  1880093      Windows

[15433 rows x 2 columns]

In [48]:
df_b.loc[:,"val"] = np.ones(len(df_b))

/var/folders/kn/2hccvkp11655sjfyptcwpt0h0000gn/T/ipykernel_70769/2254770818.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_b.loc[:,"val"] = np.ones(len(df_b))

In [49]:
df_b

           userId exact_device  val
1         1563081    Macintosh  1.0
2         1697168    Macintosh  1.0
4         1714398      Windows  1.0
5         1010522      Windows  1.0
6         1475659      Windows  1.0
...           ...          ...  ...
24727427  1004668      Windows  1.0
24729155  1306591      Windows  1.0
24751626  1910265        Linux  1.0
24766737  1662561      Windows  1.0
24817606  1880093      Windows  1.0

[15433 rows x 3 columns]

In [50]:
df_c = df_b.pivot(index = "userId", columns = "exact_device", values = "val")

In [51]:
df_c = df_c.fillna(0.0)

In [52]:
df_c

exact_device  Linux  Macintosh  Windows  iPad  iPhone
userId
1000035         1.0        0.0      0.0   0.0     0.0
1000103         1.0        0.0      0.0   0.0     0.0
1000164         0.0        0.0      1.0   0.0     0.0
1000168         1.0        0.0      0.0   0.0     0.0
1000182         0.0        1.0      0.0   0.0     0.0
...             ...        ...      ...   ...     ...
1999241         0.0        0.0      1.0   0.0     0.0
1999382         0.0        1.0      0.0   0.0     0.0
1999781         0.0        1.0      0.0   0.0     0.0
1999848         0.0        0.0      1.0   0.0     0.0
1999905         0.0        0.0      1.0   0.0     0.0

[15433 rows x 5 columns]

In [78]:
df_c = df_c.merge(df_y, on = "userId")

In [ ]:
df_c.pivot()

,userId,Linux,Macintosh,Windows,iPad,iPhone,Cancellation Confirmation
0,1000035,1.0,0.0,0.0,0.0,0.0,0
1,1000103,1.0,0.0,0.0,0.0,0.0,0
2,1000164,0.0,0.0,1.0,0.0,0.0,0
3,1000168,1.0,0.0,0.0,0.0,0.0,0
4,1000182,0.0,1.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...
15428,1999241,0.0,0.0,1.0,0.0,0.0,0
15429,1999382,0.0,1.0,0.0,0.0,0.0,0
15430,1999781,0.0,1.0,0.0,0.0,0.0,0
15431,1999848,0.0,0.0,1.0,0.0,0.0,0
15432,1999905,0.0,0.0,1.0,0.0,0.0,0

In [83]:
print(len(df_c[(df_c["Linux"] == 1.0) & (df_c["Cancellation Confirmation"] == 1)]) / len(df_c[df_c["Linux"] == 1.0]))
print(len(df_c[(df_c["Linux"] == 1.0) & (df_c["Cancellation Confirmation"] == 0)]) / len(df_c[df_c["Linux"] == 1.0]))

print(len(df_c[(df_c["Macintosh"] == 1.0) & (df_c["Cancellation Confirmation"] == 1)]) / len(df_c[df_c["Macintosh"] == 1.0]))
print(len(df_c[(df_c["Macintosh"] == 1.0) & (df_c["Cancellation Confirmation"] == 0)]) / len(df_c[df_c["Macintosh"] == 1.0]))

print(len(df_c[(df_c["Windows"] == 1.0) & (df_c["Cancellation Confirmation"] == 1)]) / len(df_c[df_c["Windows"] == 1.0]))
print(len(df_c[(df_c["Windows"] == 1.0) & (df_c["Cancellation Confirmation"] == 0)]) / len(df_c[df_c["Windows"] == 1.0]))

print(len(df_c[(df_c["iPad"] == 1.0) & (df_c["Cancellation Confirmation"] == 1)]) / len(df_c[df_c["iPad"] == 1.0]))
print(len(df_c[(df_c["iPad"] == 1.0) & (df_c["Cancellation Confirmation"] == 0)]) / len(df_c[df_c["iPad"] == 1.0]))

print(len(df_c[(df_c["iPhone"] == 1.0) & (df_c["Cancellation Confirmation"] == 1)]) / len(df_c[df_c["iPhone"] == 1.0]))
print(len(df_c[(df_c["iPhone"] == 1.0) & (df_c["Cancellation Confirmation"] == 0)]) / len(df_c[df_c["iPhone"] == 1.0]))

0.0448654037886341
0.9551345962113659
0.04716827158478864
0.9528317284152114
0.04735376044568245
0.9526462395543176
0.027149321266968326
0.9728506787330317
0.06998158379373849
0.9300184162062615

In [112]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import HistGradientBoostingClassifier, AdaBoostClassifier
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [102]:
X_columns = ['Linux', 'Macintosh', 'Windows', 'iPad', 'iPhone']
y_columns = "Cancellation Confirmation"

In [103]:
print(X_columns)
print(y_columns)

['Linux', 'Macintosh', 'Windows', 'iPad', 'iPhone']
Cancellation Confirmation

In [104]:
X = df_c[X_columns]
y = df_c[y_columns]

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [105]:
clf = HistGradientBoostingClassifier()

clf.fit(X_train, y_train)

HistGradientBoostingClassifier()

In [106]:
y_pred = clf.predict(X_test)

In [101]:
confusion_matrix(y_test, y_pred)

array([[3673,    0],
       [ 186,    0]])

In [107]:
clf = LogisticRegression(max_iter=10000)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[3705,    0],
       [ 154,    0]])

In [110]:
clf = SVC()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[3705,    0],
       [ 154,    0]])

In [113]:
clf = AdaBoostClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[3705,    0],
       [ 154,    0]])