In [1]:
import pandas as pd

In [2]:
full_dataset_df = pd.read_parquet("../../data/churn-prediction-25-26/train.parquet")

In [3]:
df_train = full_dataset_df.copy()
df_test = full_dataset_df.copy()

In [4]:
# First Test set
#cutoff_train = pd.Timestamp("2018-10-08")
#cutoff_test = pd.Timestamp("2018-10-18")

# Second Train Test set
cutoff_train = pd.Timestamp("2018-10-15")
cutoff_test = pd.Timestamp("2018-10-25")

df_train = df_train[df_train["time"] <= cutoff_train]
df_test = df_test[df_test["time"] <= cutoff_test]

In [22]:
# only consider users that haven't already cancelled their memebership
df_train["already_canceled"] = df_train["page"] == "Cancellation Confirmation"
df_train_reduced = df_train[~df_train["userId"].isin(df_train[df_train["already_canceled"]]["userId"])].copy()

In [55]:
# in the test dataset: only consider users that are in the train dataset
# create an array of the form ["userId", "Cancellation Confirmed"]

df_test_reduced = df_test[df_test["userId"].isin(df_train_reduced["userId"])].copy()
df_test_reduced["Canceled"] = df_test_reduced["page"] == "Cancellation Confirmation"
df_test_reduced["Canceled"] = df_test_reduced["Canceled"].astype(int)

In [56]:
df_test_reduced

,status,gender,firstName,level,lastName,userId,ts,auth,page,sessionId,location,itemInSession,userAgent,method,length,song,artist,time,registration,Canceled
0,200,M,Shlok,paid,Johnson,1749042,1538352001000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",278,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,524.32934,Ich mache einen Spiegel - Dream Part 4,Popol Vuh,2018-10-01 00:00:01,2018-08-08 13:22:21,0
992,200,M,Shlok,paid,Johnson,1749042,1538352525000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",279,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,178.02404,Monster (Album Version),Skillet,2018-10-01 00:08:45,2018-08-08 13:22:21,0
1360,200,M,Shlok,paid,Johnson,1749042,1538352703000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",280,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,232.61995,Seven Nation Army,The White Stripes,2018-10-01 00:11:43,2018-08-08 13:22:21,0
1825,200,M,Shlok,paid,Johnson,1749042,1538352935000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",281,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,265.50812,Under The Bridge (Album Version),Red Hot Chili Peppers,2018-10-01 00:15:35,2018-08-08 13:22:21,0
2366,200,M,Shlok,paid,Johnson,1749042,1538353200000,Logged In,NextSong,22683,"Dallas-Fort Worth-Arlington, TX",282,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",PUT,471.69261,Circlesong 6,Bobby McFerrin,2018-10-01 00:20:00,2018-08-08 13:22:21,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23704436,200,F,Alina,paid,Thompson,1511484,1539648571000,Logged In,NextSong,14020,"Washington-Arlington-Alexandria, DC-VA-MD-WV",33,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) G...,PUT,190.69342,Coil (Album Version),Opeth,2018-10-16 00:09:31,2018-09-19 19:24:56,0
23704439,307,F,Alina,paid,Thompson,1511484,1539648572000,Logged In,Thumbs Up,14020,"Washington-Arlington-Alexandria, DC-VA-MD-WV",34,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) G...,PUT,NaN,None,None,2018-10-16 00:09:32,2018-09-19 19:24:56,0
23704592,200,F,Alina,paid,Thompson,1511484,1539648761000,Logged In,NextSong,14020,"Washington-Arlington-Alexandria, DC-VA-MD-WV",35,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) G...,PUT,277.15873,Horn Concerto No. 4 in E flat K495: II. Romanc...,Barry Tuckwell/Academy of St Martin-in-the-Fie...,2018-10-16 00:12:41,2018-09-19 19:24:56,0
23704805,200,F,Alina,paid,Thompson,1511484,1539649038000,Logged In,NextSong,14020,"Washington-Arlington-Alexandria, DC-VA-MD-WV",36,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) G...,PUT,223.63383,Por La Noche,Mala Rodriguez,2018-10-16 00:17:18,2018-09-19 19:24:56,0
23704976,200,F,Alina,paid,Thompson,1511484,1539649261000,Logged In,NextSong,14020,"Washington-Arlington-Alexandria, DC-VA-MD-WV",37,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) G...,PUT,273.13587,No Woman_ No Cry,The Fugees,2018-10-16 00:21:01,2018-09-19 19:24:56,0

In [57]:
df_test_reduced[df_test_reduced["Canceled"] == 1]

,status,gender,firstName,level,lastName,userId,ts,auth,page,sessionId,location,itemInSession,userAgent,method,length,song,artist,time,registration,Canceled
6662491,200,M,Shlok,paid,Johnson,1749042,1540084584000,Cancelled,Cancellation Confirmation,100362,"Dallas-Fort Worth-Arlington, TX",62,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",GET,NaN,None,None,2018-10-21 01:16:24,2018-08-08 13:22:21,1
6515702,200,F,Maliya,paid,Hubbard,1559837,1540031004000,Cancelled,Cancellation Confirmation,100729,"Columbus, OH",391,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",GET,NaN,None,None,2018-10-20 10:23:24,2018-09-28 06:39:09,1
7411981,200,M,Konner,free,Thomas,1528783,1540299148000,Cancelled,Cancellation Confirmation,111103,"Roanoke, VA",25,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",GET,NaN,None,None,2018-10-23 12:52:28,2018-06-27 00:13:31,1
6369931,200,M,Oscar,paid,Brown,1604150,1539989073000,Cancelled,Cancellation Confirmation,83790,"Phoenix-Mesa-Scottsdale, AZ",939,Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; r...,GET,NaN,None,None,2018-10-19 22:44:33,2018-09-17 02:02:27,1
7449664,200,M,Jake,paid,Chavez,1901750,1540307186000,Cancelled,Cancellation Confirmation,107878,"Salinas, CA",111,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",GET,NaN,None,None,2018-10-23 15:06:26,2018-08-10 04:27:49,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23979194,200,F,Sophia,paid,Conner,1138673,1540002106000,Cancelled,Cancellation Confirmation,17580,"Clinton, IA",126,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5...",GET,NaN,None,None,2018-10-20 02:21:46,2018-09-30 13:33:20,1
24198118,200,F,Aleah,paid,Jones,1812526,1540379781000,Cancelled,Cancellation Confirmation,20077,"Ogden-Clearfield, UT",39,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) G...,GET,NaN,None,None,2018-10-24 11:16:21,2018-09-04 22:29:21,1
23810138,200,M,Anthony,paid,Torres,1081063,1539796595000,Cancelled,Cancellation Confirmation,14250,"Winchester, VA-WV",17,"""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK...",GET,NaN,None,None,2018-10-17 17:16:35,2018-09-29 13:39:28,1
23837187,200,F,Harmoni,free,Allison,1172943,1539826948000,Cancelled,Cancellation Confirmation,15001,"Torrington, CT",9,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",GET,NaN,None,None,2018-10-18 01:42:28,2018-08-04 20:35:20,1
23904736,200,F,Jazariah,paid,Jones,1253823,1539908632000,Cancelled,Cancellation Confirmation,12811,"Asheville, NC",20,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",GET,NaN,None,None,2018-10-19 00:23:52,2018-07-24 02:58:08,1

In [58]:
df_test_reduced["Canceled"] = df_test_reduced.groupby("userId")["Canceled"].transform("max")

In [59]:
df_test_reduced = df_test_reduced[["userId", "Canceled"]].drop_duplicates()

In [60]:
df_test_reduced[]

           userId  Canceled
0         1749042         1
1         1563081         0
2         1697168         0
3         1222580         0
4         1714398         0
...           ...       ...
23634698  1875963         0
23636477  1953008         0
23637666  1296522         0
23639387  1503406         0
23640258  1511484         0

[14832 rows x 2 columns]

           userId  Canceled
0         1749042         1
34        1559837         1
76        1528783         1
94        1604150         1
122       1901750         1
...           ...       ...
23045462  1138673         1
23053068  1812526         1
23055136  1081063         1
23103759  1172943         1
23211249  1253823         1

[826 rows x 2 columns]

In [39]:
df_test_reduced["userId"].nunique()

14832

In [38]:
df_test_reduced["userId"].nunique()

14832